config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :bookings do
    resources:bookitems
  end
  #resources :orders
  devise_for :users do
    resources:bookings
  end
 

  resources :items
  
  root 'static_pages#home'
  
  get 'cart/index'
  
  get '/about'=>'static_pages#about'

  get '/contact'=>'static_pages#contact'
  
  get '/menu' => 'items#index'
  
  get '/login' => 'user#login'
  
  get '/logout' => 'user#logout'
  
  get '/register' => 'user#register'
  
  get '/cart' => 'cart#index'
  
  get '/cart/:id' => 'cart#add'
  
  get '/my_bookings' => 'bookings#index'
  
  get '/cart' => 'cart#index'
  
  get '/clearcart' => 'cart#clearcart'
  
  get '/remove/:id' => 'cart#remove'
  
  get '/decrease/:id' => 'cart#decrease'
  
  get '/increase/:id' => 'cart#increase'
  
  get '/checkout' => 'cart#createBooking'
  
  get '/admin' => 'static_pages#adminsection'
  
  get '/paid/:id' => 'static_pages#paid'
  
  post '/search' => 'items#search'
  
  get '/category/:title' => 'static_pages#category'
  
  get '/upgrade_admin/:id' => 'static_pages#upgrade_admin'
  
  get '/downgrade_admin/:id' => 'static_pages#downgrade_admin'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all
    @items = Item.all
  end

  def menu
     
  end

  def about
  end

  def contact
    #session[:cart] = nil
  end
  
  
  def adminsection
    @bookings = Booking.all
    @users = User.all
  end 
  
  
  def paid
    @booking = Booking.last
    @booking.update_attribute(:status, 'Paid')
  end
  
  def category
    cat = params[:title]
    @items = Item.where("category like ?", cat)
  end
  
  
  def upgrade_admin
    @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, true)
    redirect_to "/"
  end
  
  def downgrade_admin
    @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, false)
    redirect_to "/"
  end    
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%provide(:title,"About")%>
<div class="w3-container w3-padding-64 w3-red w3-grayscale w3-xlarge" id="about">
  <div class="w3-content">
    <h1 class="w3-center w3-jumbo" style="margin-bottom:64px">About</h1>
    <p> Restaurant La Consegna  was founded by Mr. Giuseppe Luicini in Torino. Giuseppe  was running the restaurant in Torino for 15 years, when he moved to Ireland and established An authentic Italian restaurant in Dublin. La Consegna restaurant is now Ireland`s leading friendly Italian restaurants. From pizza to pasta and desserts, we offer home-made dishes. Our pizza chef is a world champion, our head chef is young Italian pro. Our team are ready to welcome you. We offer 100 % fast and reliable delivery. Choose from our menu and we will deliver to your home. </p> 
    <b>Opening Hours</b>
    
    <div class="w3-row">
      <div class="w3-col s6">
        <p>Sunday & Monday CLOSED</p>
        <p>Tuesday & Wednesday 5pm - 10pm</p>
        <p>Thursday 5pm - 11pm</p>
      </div>
      <div class="w3-col s6">
        <p>Friday 5pm - 12pm</p>
        <p>Saturday 3pm - 12.30pm</p>
      </div>
    </div>
    
  </div>
</div> 

app/views/static_pages/adminsection.html.erb
<% if user_signed_in? && current_user.admin? %>
<p id="notice"><%= notice %></p>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking_date %></td>
        <td><%= booking.user.email %></td>
        <td><%= booking.status %></td>
        <td><%= link_to 'Show', booking, :class => "button", :role => "button" %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking), :class => "button", :role => "button" %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %></td>
      </tr>  
  
    <% end %>
   </tbody>
  </table>
 </div>
</div>


<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
 <% @users.each do |user| %>
   <h2>Id <%= user.id %></h2>
   <h2>Id <%= user.email %></h2>
   <h2>Role <%= user.admin %></h2>
   <a href="/upgrade_admin/<%= user.id %>" class="button">Make <%= user.email %> Admin</a>
   <a href="/downgrade_admin/<%= user.id %>" class="button">Remove <%= user.email %> Admin</a>
 <% end %>
 </div>
 
</div>



<% else %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-red">
    <h1>Sorry, this section is only for Admin!!!</h1>
  </div>
</div> 
    
<% end %>
   


 

 


 
   

app/views/static_pages/category.html.erb
 <% if @items.length == 0 %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h2>Sorry, there is no a meal matching your search!</h2> 
  </div>
</div>

<% else %>
   
<p id="notice"><%= notice %></p>

<!-- Menu Container -->
<div class="w3-container w3-black w3-padding-64 w3-xxlarge" id="menu">
  <div class="w3-content">
    <h1 class="w3-center w3-jumbo" style="margin-bottom:64px">MENU</h1>
    
    <% @items.each do |item| %>
     <div class="w3-row w3-center w3-border w3-border-dark-grey">
        <div class="w3-col s4 tablink w3-padding-large w3-hover-red"><p><%=item.category%></p></div>
           <div id="Pizza" class="w3-container menu w3-padding-32 w3-white">
           <h1><b><%=item.title%></b> <span class="w3-right w3-tag w3-dark-grey w3-round"><%= number_to_currency(item.price, :unit => "€") %></span></h1>
	       <a href="/cart/<%= item.id %>"class="w3-right w3-tag w3-hover-red w3-round">ADD TO CART</a>
           <p class="w3-text-grey"><%=item.description%></p>
           <hr>
           <p>
           <%= link_to 'Show',  item, :class => "button", :role => "button" %>
           <% if user_signed_in? && current_user.admin? %>
              <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
              <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
              <%= link_to 'New Item',  new_item_path, :class => "button", :role => "button" %>
            <% end %>
            
           </p>
           </div>
    <%end%>
     </div>
   </div> 
</div>
<br>
<% end %>
 
   

app/views/static_pages/contact.html.erb
<%provide(:title,"Contact")%>
<div class="w3-container w3-padding-64 w3-blue-grey w3-grayscale-min w3-xlarge">
  <div class="w3-content">
    <h1 class="w3-center w3-jumbo" style="margin-bottom:64px">Contact</h1>
    <p>Find us at Camden street, Dublin 2 or call us at 05050515-122330</p>
    <p><span class="w3-tag">FYI!</span> We offer full-service catering for any event, large or small. We understand your needs and we will cater the food to satisfy the biggerst criteria of them all, both look and taste.</p>
    <p class="w3-xxlarge"><strong>Reserve</strong> a table, ask for today's special or just send us a message</p>
  </div>
</div> 

app/views/static_pages/home.html.erb
<%provide(:title,"Home")%>
<div class="mainCont">
<%= image_tag("pizza.jpeg", alt: "Welcome Logo", :class => "pizza") %>    
</div> 
<div class="w3-display-middle w3-center">
     
    <p class="w3-button w3-xxlarge w3-black" style="text-decoration:none"><%= link_to "LET ME SEE THE MENU", "/menu" %></p>
</div>

<div class="mainCont">
    <h1>Categories</h1>
    <% @categories.each do |category| %>
    <div class="grid-container"> 
      <div class="category"><%= category.title %></div>
      <a href="/category/<%= category.title %>"><div class="category"><img src="/assets/<%= category.image %>"alt="<%= category.title %>"></div></a>
      <div class="category"><%= category.description %></div>
    </div>
    <% end %>
</div>

 <%=render 'layouts/popular'%>

app/views/static_pages/menu.html.erb
<%provide(:title,"Menu")%>
 

app/views/static_pages/paid.html.erb
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>Thank you! I have received your payment!</h1>

<%= image_tag("yes.jpeg", alt: "Confirmed", :class => "yes") %> 
  </div>
  <%= link_to 'Back', items_path, :class => "button", :role => "button" %>
</div>