config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :bookings do
    resources:bookitems
  end
  #resources :orders
  devise_for :users do
    resources:bookings
  end
 

  resources :items
  
  root 'static_pages#home'
  
  get 'cart/index'
  
  get '/about'=>'static_pages#about'

  get '/contact'=>'static_pages#contact'
  
  get '/menu' => 'items#index'
  
  get '/login' => 'user#login'
  
  get '/logout' => 'user#logout'
  
  get '/register' => 'user#register'
  
  get '/cart' => 'cart#index'
  
  get '/cart/:id' => 'cart#add'
  
  get '/my_bookings' => 'bookings#index'
  
  get '/cart' => 'cart#index'
  
  get '/clearcart' => 'cart#clearcart'
  
  get '/remove/:id' => 'cart#remove'
  
  get '/decrease/:id' => 'cart#decrease'
  
  get '/increase/:id' => 'cart#increase'
  
  get '/checkout' => 'cart#createBooking'
  
  get '/admin' => 'static_pages#adminsection'
  
  get '/paid/:id' => 'static_pages#paid'
  
  post '/search' => 'items#search'
  
  get '/category/:title' => 'static_pages#category'
  
  get '/upgrade_admin/:id' => 'static_pages#upgrade_admin'
  
  get '/downgrade_admin/:id' => 'static_pages#downgrade_admin'
  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :bookitems
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @user = User.find(current_user.id)
    @bookings = @user.bookings.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @bookitems = Bookitem.where(booking_id: params[:id])
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:booking_date, :user_id, :status)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="newItemForm">
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :booking_date %>
    <%= f.datetime_select :booking_date %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/bookings/edit.html.erb
<% if user_signed_in? && current_user.admin? %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>
</br>

<%= link_to 'Show', @booking, :class => "button", :role => "button" %> 
<%= link_to 'Back', bookings_path, :class => "button", :role => "button" %>
<%= link_to 'Destroy', @booking, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %></td>

  </div>
</div>
<% else %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-red">
    <h1>Sorry, this section is only for Admin!!!</h1>
  </div>
</div> 
<% end %>
 
   

app/views/bookings/index.html.erb
<% if current_user.admin? %>
<p id="notice"><%= notice %></p>

<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking_date %></td>
        <td><%= booking.user.email %></td>
        <td><%= booking.status %></td>
        <td><%= link_to 'Show', booking, :class => "button", :role => "button" %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking), :class => "button", :role => "button" %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path, :class => "button", :role => "button" %>
  </div>
</div>

<% else %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Booking date</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking_date %></td>
        <td><%= booking.user.email %></td>
        <td><%= booking.status %></td>
        <td><%= link_to 'Show', booking, :class => "button", :role => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 </div>
</div>
<% end %>

  
 
  
 

app/views/bookings/new.html.erb
<% if user_signed_in? && current_user.admin? %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>
  </div>
</div>
<% else %>
<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-red">
<h1>Sorry, you can not edit bookings</h1>
<% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<% if @booking.user.email == current_user.email %>
<p id="notice"><%= notice %></p>

<div class="w3-row w3-center w3-border w3-border-dark-grey">
  <div id="Pizza" class="w3-container menu w3-padding-32 w3-sand">

<p>
  <strong>Booking date:</strong>
  <%= @booking.booking_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @booking.status %>
</p>

  </div>
</div>

<div id="itemsContainer">
    <table id="customers">
        <tr>
            <th>Meal</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Meal cost</th>
        </tr>
        
          <% total = 0 %>
           
          <% @bookitems.each do |id, quantity| %>
          <% item = Bookitem.find_by_id(id) %>
        <tr>
            <td class="title"><%= item.title %></td>
            <td class="price"><%= number_to_currency(item.price, :unit =>"€") %></td>
            <td class="quantity"><%= item.quantity %></td>
            <td class="price"><%= number_to_currency(item.quantity * item.price, :unit =>"€") %></td>
        </tr>
        
        <% total += item.quantity * item.price %>
        <% end %>
        
        <tr>
            <td>Total: <%= number_to_currency(total, :unit =>"€") %></td>
        </tr>
        
    </table>
     
  </div>
  
  <% else %>
  <div class="w3-row w3-center w3-border w3-border-dark-grey">
     <div id="Pizza" class="w3-container menu w3-padding-32 w3-red">
  <h1>Sorry, this does not belong to you!!!</h1>
     </div>
  </div>
  <% end %>